CREATE DATABASE  groupomania charset=utf8;
USE groupomania;

CREATE TABLE IF NOT EXISTS users(
    id SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    familyName VARCHAR(30) NOT NULL,
    firstName VARCHAR(30) NOT NULL
)
ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS account(
    account_id SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    email VARCHAR(60) NOT NULL UNIQUE,
    password TEXT NOT NULL
)
